import type { Block } from 'payload'

const mrCities = [
  'Mr. California ™',
  'Mr. Adelanto ™',
  'Mr. Agoura Hills ™',
  'Mr. Alameda ™',
  'Mr. Albany ™',
  'Mr. Alhambra ™',
  'Mr. Aliso Viejo ™',
  'Mr. Alturas ™',
  'Mr. Amador City ™',
  'Mr. American Canyon ™',
  'Mr. Anaheim ™',
  'Mr. Anderson ™',
  'Mr. Angels Camp ™',
  'Mr. Antioch ™',
  'Mr. Apple Valley ™',
  'Mr. Arcadia ™',
  'Mr. Arcata ™',
  'Mr. Arroyo Grande ™',
  'Mr. Artesia ™',
  'Mr. Arvin ™',
  'Mr. Atascadero ™',
  'Mr. Atherton ™',
  'Mr. Atwater ™',
  'Mr. Auburn ™',
  'Mr. Avalon ™',
  'Mr. Avenal ™',
  'Mr. Azusa ™',
  'Mr. Bakersfield ™',
  'Mr. Baldwin Park ™',
  'Mr. Banning ™',
  'Mr. Barstow ™',
  'Mr. Beaumont ™',
  'Mr. Bell ™',
  'Mr. Bell Gardens ™',
  'Mr. Bellflower ™',
  'Mr. Belmont ™',
  'Mr. Belvedere ™',
  'Mr. Benicia ™',
  'Mr. Berkeley ™',
  'Mr. Beverly Hills ™',
  'Mr. Big Bear Lake ™',
  'Mr. Biggs ™',
  'Mr. Bishop ™',
  'Mr. Blue Lake ™',
  'Mr. Blythe ™',
  'Mr. Bradbury ™',
  'Mr. Brawley ™',
  'Mr. Brea ™',
  'Mr. Brentwood ™',
  'Mr. Brisbane ™',
  'Mr. Buellton ™',
  'Mr. Buena Park ™',
  'Mr. Burbank ™',
  'Mr. Burlingame ™',
  'Mr. Calabasas ™',
  'Mr. Calexico ™',
  'Mr. California City ™',
  'Mr. Calimesa ™',
  'Mr. Calipatria ™',
  'Mr. Calistoga ™',
  'Mr. Camarillo ™',
  'Mr. Campbell ™',
  'Mr. Canyon Lake ™',
  'Mr. Capitola ™',
  'Mr. Carlsbad ™',
  'Mr. Carmel-by-the-Sea ™',
  'Mr. Carpinteria ™',
  'Mr. Carson ™',
  'Mr. Cathedral City ™',
  'Mr. Ceres ™',
  'Mr. Cerritos ™',
  'Mr. Chico ™',
  'Mr. Chino ™',
  'Mr. Chino Hills ™',
  'Mr. Chowchilla ™',
  'Mr. Chula Vista ™',
  'Mr. Citrus Heights ™',
  'Mr. Claremont ™',
  'Mr. Clayton ™',
  'Mr. Clearlake ™',
  'Mr. Cloverdale ™',
  'Mr. Clovis ™',
  'Mr. Coachella ™',
  'Mr. Coalinga ™',
  'Mr. Colfax ™',
  'Mr. Colma ™',
  'Mr. Colton ™',
  'Mr. Colusa ™',
  'Mr. Commerce ™',
  'Mr. Compton ™',
  'Mr. Concord ™',
  'Mr. Corcoran ™',
  'Mr. Corning ™',
  'Mr. Corona ™',
  'Mr. Coronado ™',
  'Mr. Corte Madera ™',
  'Mr. Costa Mesa ™',
  'Mr. Cotati ™',
  'Mr. Covina ™',
  'Mr. Crescent City ™',
  'Mr. Cudahy ™',
  'Mr. Culver City ™',
  'Mr. Cupertino ™',
  'Mr. Cypress ™',
  'Mr. Daly City ™',
  'Mr. Dana Point ™',
  'Mr. Danville ™',
  'Mr. Davis ™',
  'Mr. Del Mar ™',
  'Mr. Del Rey Oaks ™',
  'Mr. Delano ™',
  'Mr. Desert Hot Springs ™',
  'Mr. Diamond Bar ™',
  'Mr. Dinuba ™',
  'Mr. Dixon ™',
  'Mr. Dorris ™',
  'Mr. Dos Palos ™',
  'Mr. Downey ™',
  'Mr. Duarte ™',
  'Mr. Dublin ™',
  'Mr. Dunsmuir ™',
  'Mr. East Palo Alto ™',
  'Mr. Eastvale ™',
  'Mr. El Cajon ™',
  'Mr. El Centro ™',
  'Mr. El Cerrito ™',
  'Mr. El Monte ™',
  'Mr. El Segundo ™',
  'Mr. Elk Grove ™',
  'Mr. Emeryville ™',
  'Mr. Encinitas ™',
  'Mr. Escalon ™',
  'Mr. Escondido ™',
  'Mr. Etna ™',
  'Mr. Eureka ™',
  'Mr. Exeter ™',
  'Mr. Fairfax ™',
  'Mr. Fairfield ™',
  'Mr. Farmersville ™',
  'Mr. Ferndale ™',
  'Mr. Fillmore ™',
  'Mr. Firebaugh ™',
  'Mr. Folsom ™',
  'Mr. Fontana ™',
  'Mr. Fort Bragg ™',
  'Mr. Fort Jones ™',
  'Mr. Fortuna ™',
  'Mr. Foster City ™',
  'Mr. Fountain Valley ™',
  'Mr. Fowler ™',
  'Mr. Fremont ™',
  'Mr. Fresno ™',
  'Mr. Fullerton ™',
  'Mr. Galt ™',
  'Mr. Garden Grove ™',
  'Mr. Gardena ™',
  'Mr. Gilroy ™',
  'Mr. Glendale ™',
  'Mr. Glendora ™',
  'Mr. Goleta ™',
  'Mr. Gonzales ™',
  'Mr. Grand Terrace ™',
  'Mr. Grass Valley ™',
  'Mr. Greenfield ™',
  'Mr. Gridley ™',
  'Mr. Grover Beach ™',
  'Mr. Guadalupe ™',
  'Mr. Gustine ™',
  'Mr. Half Moon Bay ™',
  'Mr. Hanford ™',
  'Mr. Hawaiian Gardens ™',
  'Mr. Hawthorne ™',
  'Mr. Hayward ™',
  'Mr. Healdsburg ™',
  'Mr. Hemet ™',
  'Mr. Hercules ™',
  'Mr. Hermosa Beach ™',
  'Mr. Hesperia ™',
  'Mr. Hidden Hills ™',
  'Mr. Highland ™',
  'Mr. Hillsborough ™',
  'Mr. Hollister ™',
  'Mr. Holtville ™',
  'Mr. Hughson ™',
  'Mr. Huntington Beach ™',
  'Mr. Huntington Park ™',
  'Mr. Huron ™',
  'Mr. Imperial ™',
  'Mr. Imperial Beach ™',
  'Mr. Indian Wells ™',
  'Mr. Indio ™',
  'Mr. Industry ™',
  'Mr. Inglewood ™',
  'Mr. Ione ™',
  'Mr. Irvine ™',
  'Mr. Irwindale ™',
  'Mr. Isleton ™',
  'Mr. Jackson ™',
  'Mr. Jurupa Valley ™',
  'Mr. Kerman ™',
  'Mr. King City ™',
  'Mr. Kingsburg ™',
  'Mr. La Cañada Flintridge ™',
  'Mr. La Habra ™',
  'Mr. La Habra Heights ™',
  'Mr. La Mesa ™',
  'Mr. La Mirada ™',
  'Mr. La Palma ™',
  'Mr. La Puente ™',
  'Mr. La Quinta ™',
  'Mr. La Verne ™',
  'Mr. Lafayette ™',
  'Mr. Laguna Beach ™',
  'Mr. Laguna Hills ™',
  'Mr. Laguna Niguel ™',
  'Mr. Laguna Woods ™',
  'Mr. Lake Elsinore ™',
  'Mr. Lake Forest ™',
  'Mr. Lakeport ™',
  'Mr. Lakewood ™',
  'Mr. Lancaster ™',
  'Mr. Larkspur ™',
  'Mr. Lathrop ™',
  'Mr. Lawndale ™',
  'Mr. Lemon Grove ™',
  'Mr. Lemoore ™',
  'Mr. Lincoln ™',
  'Mr. Lindsay ™',
  'Mr. Live Oak ™',
  'Mr. Livermore ™',
  'Mr. Livingston ™',
  'Mr. Lodi ™',
  'Mr. Loma Linda ™',
  'Mr. Lomita ™',
  'Mr. Lompoc ™',
  'Mr. Long Beach ™',
  'Mr. Loomis ™',
  'Mr. Los Alamitos ™',
  'Mr. Los Altos ™',
  'Mr. Los Altos Hills ™',
  'Mr. Los Angeles ™',
  'Mr. Los Banos ™',
  'Mr. Los Gatos ™',
  'Mr. Loyalton ™',
  'Mr. Lynwood ™',
  'Mr. Madera ™',
  'Mr. Malibu ™',
  'Mr. Mammoth Lakes ™',
  'Mr. Manhattan Beach ™',
  'Mr. Manteca ™',
  'Mr. Maricopa ™',
  'Mr. Marina ™',
  'Mr. Martinez ™',
  'Mr. Marysville ™',
  'Mr. Maywood ™',
  'Mr. McFarland ™',
  'Mr. Mendota ™',
  'Mr. Menifee ™',
  'Mr. Menlo Park ™',
  'Mr. Merced ™',
  'Mr. Mill Valley ™',
  'Mr. Millbrae ™',
  'Mr. Milpitas ™',
  'Mr. Mission Viejo ™',
  'Mr. Modesto ™',
  'Mr. Monrovia ™',
  'Mr. Montague ™',
  'Mr. Montclair ™',
  'Mr. Monte Sereno ™',
  'Mr. Montebello ™',
  'Mr. Monterey ™',
  'Mr. Monterey Park ™',
  'Mr. Moorpark ™',
  'Mr. Moraga ™',
  'Mr. Moreno Valley ™',
  'Mr. Morgan Hill ™',
  'Mr. Morro Bay ™',
  'Mr. Mount Shasta ™',
  'Mr. Mountain View ™',
  'Mr. Murrieta ™',
  'Mr. Napa ™',
  'Mr. National City ™',
  'Mr. Needles ™',
  'Mr. Nevada City ™',
  'Mr. Newark ™',
  'Mr. Newman ™',
  'Mr. Newport Beach ™',
  'Mr. Norco ™',
  'Mr. Norwalk ™',
  'Mr. Novato ™',
  'Mr. Oakdale ™',
  'Mr. Oakland ™',
  'Mr. Oakley ™',
  'Mr. Oceanside ™',
  'Mr. Ojai ™',
  'Mr. Ontario ™',
  'Mr. Orange ™',
  'Mr. Orange Cove ™',
  'Mr. Orinda ™',
  'Mr. Orland ™',
  'Mr. Oroville ™',
  'Mr. Oxnard ™',
  'Mr. Pacific Grove ™',
  'Mr. Pacifica ™',
  'Mr. Palm Desert ™',
  'Mr. Palm Springs ™',
  'Mr. Palmdale ™',
  'Mr. Palo Alto ™',
  'Mr. Palos Verdes Estates ™',
  'Mr. Paradise ™',
  'Mr. Paramount ™',
  'Mr. Parlier ™',
  'Mr. Pasadena ™',
  'Mr. Paso Robles ™',
  'Mr. Patterson ™',
  'Mr. Perris ™',
  'Mr. Petaluma ™',
  'Mr. Pico Rivera ™',
  'Mr. Piedmont ™',
  'Mr. Pinole ™',
  'Mr. Pismo Beach ™',
  'Mr. Pittsburg ™',
  'Mr. Placentia ™',
  'Mr. Placerville ™',
  'Mr. Pleasant Hill ™',
  'Mr. Pleasanton ™',
  'Mr. Plymouth ™',
  'Mr. Point Arena ™',
  'Mr. Pomona ™',
  'Mr. Port Hueneme ™',
  'Mr. Porterville ™',
  'Mr. Portola ™',
  'Mr. Portola Valley ™',
  'Mr. Poway ™',
  'Mr. Rancho Cordova ™',
  'Mr. Rancho Cucamonga ™',
  'Mr. Rancho Mirage ™',
  'Mr. Rancho Palos Verdes ™',
  'Mr. Rancho Santa Margarita ™',
  'Mr. Red Bluff ™',
  'Mr. Redding ™',
  'Mr. Redlands ™',
  'Mr. Redondo Beach ™',
  'Mr. Redwood City ™',
  'Mr. Reedley ™',
  'Mr. Rialto ™',
  'Mr. Richmond ™',
  'Mr. Ridgecrest ™',
  'Mr. Rio Dell ™',
  'Mr. Rio Vista ™',
  'Mr. Ripon ™',
  'Mr. Riverbank ™',
  'Mr. Riverside ™',
  'Mr. Rocklin ™',
  'Mr. Rohnert Park ™',
  'Mr. Rolling Hills ™',
  'Mr. Rolling Hills Estates ™',
  'Mr. Rosemead ™',
  'Mr. Roseville ™',
  'Mr. Ross ™',
  'Mr. Sacramento ™',
  'Mr. St. Helena ™',
  'Mr. Salinas ™',
  'Mr. San Anselmo ™',
  'Mr. San Bernardino ™',
  'Mr. San Bruno ™',
  'Mr. San Carlos ™',
  'Mr. San Clemente ™',
  'Mr. San Diego ™',
  'Mr. San Dimas ™',
  'Mr. San Fernando ™',
  'Mr. San Francisco ™',
  'Mr. San Gabriel ™',
  'Mr. San Jacinto ™',
  'Mr. San Joaquin ™',
  'Mr. San Jose ™',
  'Mr. San Juan Bautista ™',
  'Mr. San Juan Capistrano ™',
  'Mr. San Leandro ™',
  'Mr. San Luis Obispo ™',
  'Mr. San Marcos ™',
  'Mr. San Marino ™',
  'Mr. San Mateo ™',
  'Mr. San Pablo ™',
  'Mr. San Rafael ™',
  'Mr. San Ramon ™',
  'Mr. Sand City ™',
  'Mr. Sanger ™',
  'Mr. Santa Ana ™',
  'Mr. Santa Barbara ™',
  'Mr. Santa Clara ™',
  'Mr. Santa Clarita ™',
  'Mr. Santa Cruz ™',
  'Mr. Santa Fe Springs ™',
  'Mr. Santa Maria ™',
  'Mr. Santa Monica ™',
  'Mr. Santa Paula ™',
  'Mr. Santa Rosa ™',
  'Mr. Santee ™',
  'Mr. Saratoga ™',
  'Mr. Sausalito ™',
  'Mr. Scotts Valley ™',
  'Mr. Seal Beach ™',
  'Mr. Seaside ™',
  'Mr. Sebastopol ™',
  'Mr. Selma ™',
  'Mr. Shafter ™',
  'Mr. Shasta Lake ™',
  'Mr. Sierra Madre ™',
  'Mr. Signal Hill ™',
  'Mr. Simi Valley ™',
  'Mr. Solana Beach ™',
  'Mr. Soledad ™',
  'Mr. Solvang ™',
  'Mr. Sonoma ™',
  'Mr. Sonora ™',
  'Mr. South El Monte ™',
  'Mr. South Gate ™',
  'Mr. South Lake Tahoe ™',
  'Mr. South Pasadena ™',
  'Mr. South San Francisco ™',
  'Mr. Stanton ™',
  'Mr. Stockton ™',
  'Mr. Suisun City ™',
  'Mr. Sunnyvale ™',
  'Mr. Susanville ™',
  'Mr. Sutter Creek ™',
  'Mr. Taft ™',
  'Mr. Tehachapi ™',
  'Mr. Tehama ™',
  'Mr. Temecula ™',
  'Mr. Temple City ™',
  'Mr. Thousand Oaks ™',
  'Mr. Tiburon ™',
  'Mr. Torrance ™',
  'Mr. Tracy ™',
  'Mr. Trinidad ™',
  'Mr. Truckee ™',
  'Mr. Tulare ™',
  'Mr. Tulelake ™',
  'Mr. Turlock ™',
  'Mr. Tustin ™',
  'Mr. Twentynine Palms ™',
  'Mr. Ukiah ™',
  'Mr. Union City ™',
  'Mr. Upland ™',
  'Mr. Vacaville ™',
  'Mr. Vallejo ™',
  'Mr. Vernon ™',
  'Mr. Victorville ™',
  'Mr. Villa Park ™',
  'Mr. Visalia ™',
  'Mr. Vista ™',
  'Mr. Walnut ™',
  'Mr. Walnut Creek ™',
  'Mr. Wasco ™',
  'Mr. Waterford ™',
  'Mr. Watsonville ™',
  'Mr. Weed ™',
  'Mr. West Covina ™',
  'Mr. West Hollywood ™',
  'Mr. West Sacramento ™',
  'Mr. Westlake Village ™',
  'Mr. Westminster ™',
  'Mr. Westmorland ™',
  'Mr. Wheatland ™',
  'Mr. Whittier ™',
  'Mr. Williams ™',
  'Mr. Willits ™',
  'Mr. Willows ™',
  'Mr. Windsor ™',
  'Mr. Winters ™',
  'Mr. Woodlake ™',
  'Mr. Woodland ™',
  'Mr. Woodside ™',
  'Mr. Yorba Linda ™',
  'Mr. Yountville ™',
  'Mr. Yreka ™',
  'Mr. Yuba City ™',
  'Mr. Yucaipa ™',
  'Mr. Yucca Valley ™',
  'Mr. Inland Empire ™',
  'Mr. San Gabriel Valley ™',
]

const msCities = [
  'Ms. California ™',
  'Ms. Adelanto ™',
  'Ms. Agoura Hills ™',
  'Ms. Alameda ™',
  'Ms. Albany ™',
  'Ms. Alhambra ™',
  'Ms. Aliso Viejo ™',
  'Ms. Alturas ™',
  'Ms. Amador City ™',
  'Ms. American Canyon ™',
  'Ms. Anaheim ™',
  'Ms. Anderson ™',
  'Ms. Angels Camp ™',
  'Ms. Antioch ™',
  'Ms. Apple Valley ™',
  'Ms. Arcadia ™',
  'Ms. Arcata ™',
  'Ms. Arroyo Grande ™',
  'Ms. Artesia ™',
  'Ms. Arvin ™',
  'Ms. Atascadero ™',
  'Ms. Atherton ™',
  'Ms. Atwater ™',
  'Ms. Auburn ™',
  'Ms. Avalon ™',
  'Ms. Avenal ™',
  'Ms. Azusa ™',
  'Ms. Bakersfield ™',
  'Ms. Baldwin Park ™',
  'Ms. Banning ™',
  'Ms. Barstow ™',
  'Ms. Beaumont ™',
  'Ms. Bell ™',
  'Ms. Bell Gardens ™',
  'Ms. Bellflower ™',
  'Ms. Belmont ™',
  'Ms. Belvedere ™',
  'Ms. Benicia ™',
  'Ms. Berkeley ™',
  'Ms. Beverly Hills ™',
  'Ms. Big Bear Lake ™',
  'Ms. Biggs ™',
  'Ms. Bishop ™',
  'Ms. Blue Lake ™',
  'Ms. Blythe ™',
  'Ms. Bradbury ™',
  'Ms. Brawley ™',
  'Ms. Brea ™',
  'Ms. Brentwood ™',
  'Ms. Brisbane ™',
  'Ms. Buellton ™',
  'Ms. Buena Park ™',
  'Ms. Burbank ™',
  'Ms. Burlingame ™',
  'Ms. Calabasas ™',
  'Ms. Calexico ™',
  'Ms. California City ™',
  'Ms. Calimesa ™',
  'Ms. Calipatria ™',
  'Ms. Calistoga ™',
  'Ms. Camarillo ™',
  'Ms. Campbell ™',
  'Ms. Canyon Lake ™',
  'Ms. Capitola ™',
  'Ms. Carlsbad ™',
  'Ms. Carmel-by-the-Sea ™',
  'Ms. Carpinteria ™',
  'Ms. Carson ™',
  'Ms. Cathedral City ™',
  'Ms. Ceres ™',
  'Ms. Cerritos ™',
  'Ms. Chico ™',
  'Ms. Chino ™',
  'Ms. Chino Hills ™',
  'Ms. Chowchilla ™',
  'Ms. Chula Vista ™',
  'Ms. Citrus Heights ™',
  'Ms. Claremont ™',
  'Ms. Clayton ™',
  'Ms. Clearlake ™',
  'Ms. Cloverdale ™',
  'Ms. Clovis ™',
  'Ms. Coachella ™',
  'Ms. Coalinga ™',
  'Ms. Colfax ™',
  'Ms. Colma ™',
  'Ms. Colton ™',
  'Ms. Colusa ™',
  'Ms. Commerce ™',
  'Ms. Compton ™',
  'Ms. Concord ™',
  'Ms. Corcoran ™',
  'Ms. Corning ™',
  'Ms. Corona ™',
  'Ms. Coronado ™',
  'Ms. Corte Madera ™',
  'Ms. Costa Mesa ™',
  'Ms. Cotati ™',
  'Ms. Covina ™',
  'Ms. Crescent City ™',
  'Ms. Cudahy ™',
  'Ms. Culver City ™',
  'Ms. Cupertino ™',
  'Ms. Cypress ™',
  'Ms. Daly City ™',
  'Ms. Dana Point ™',
  'Ms. Danville ™',
  'Ms. Davis ™',
  'Ms. Del Mar ™',
  'Ms. Del Rey Oaks ™',
  'Ms. Delano ™',
  'Ms. Desert Hot Springs ™',
  'Ms. Diamond Bar ™',
  'Ms. Dinuba ™',
  'Ms. Dixon ™',
  'Ms. Dorris ™',
  'Ms. Dos Palos ™',
  'Ms. Downey ™',
  'Ms. Duarte ™',
  'Ms. Dublin ™',
  'Ms. Dunsmuir ™',
  'Ms. East Palo Alto ™',
  'Ms. Eastvale ™',
  'Ms. El Cajon ™',
  'Ms. El Centro ™',
  'Ms. El Cerrito ™',
  'Ms. El Monte ™',
  'Ms. El Segundo ™',
  'Ms. Elk Grove ™',
  'Ms. Emeryville ™',
  'Ms. Encinitas ™',
  'Ms. Escalon ™',
  'Ms. Escondido ™',
  'Ms. Etna ™',
  'Ms. Eureka ™',
  'Ms. Exeter ™',
  'Ms. Fairfax ™',
  'Ms. Fairfield ™',
  'Ms. Farmersville ™',
  'Ms. Ferndale ™',
  'Ms. Fillmore ™',
  'Ms. Firebaugh ™',
  'Ms. Folsom ™',
  'Ms. Fontana ™',
  'Ms. Fort Bragg ™',
  'Ms. Fort Jones ™',
  'Ms. Fortuna ™',
  'Ms. Foster City ™',
  'Ms. Fountain Valley ™',
  'Ms. Fowler ™',
  'Ms. Fremont ™',
  'Ms. Fresno ™',
  'Ms. Fullerton ™',
  'Ms. Galt ™',
  'Ms. Garden Grove ™',
  'Ms. Gardena ™',
  'Ms. Gilroy ™',
  'Ms. Glendale ™',
  'Ms. Glendora ™',
  'Ms. Goleta ™',
  'Ms. Gonzales ™',
  'Ms. Grand Terrace ™',
  'Ms. Grass Valley ™',
  'Ms. Greenfield ™',
  'Ms. Gridley ™',
  'Ms. Grover Beach ™',
  'Ms. Guadalupe ™',
  'Ms. Gustine ™',
  'Ms. Half Moon Bay ™',
  'Ms. Hanford ™',
  'Ms. Hawaiian Gardens ™',
  'Ms. Hawthorne ™',
  'Ms. Hayward ™',
  'Ms. Healdsburg ™',
  'Ms. Hemet ™',
  'Ms. Hercules ™',
  'Ms. Hermosa Beach ™',
  'Ms. Hesperia ™',
  'Ms. Hidden Hills ™',
  'Ms. Highland ™',
  'Ms. Hillsborough ™',
  'Ms. Hollister ™',
  'Ms. Holtville ™',
  'Ms. Hughson ™',
  'Ms. Huntington Beach ™',
  'Ms. Huntington Park ™',
  'Ms. Huron ™',
  'Ms. Imperial ™',
  'Ms. Imperial Beach ™',
  'Ms. Indian Wells ™',
  'Ms. Indio ™',
  'Ms. Industry ™',
  'Ms. Inglewood ™',
  'Ms. Ione ™',
  'Ms. Irvine ™',
  'Ms. Irwindale ™',
  'Ms. Isleton ™',
  'Ms. Jackson ™',
  'Ms. Jurupa Valley ™',
  'Ms. Kerman ™',
  'Ms. King City ™',
  'Ms. Kingsburg ™',
  'Ms. La Cañada Flintridge ™',
  'Ms. La Habra ™',
  'Ms. La Habra Heights ™',
  'Ms. La Mesa ™',
  'Ms. La Mirada ™',
  'Ms. La Palma ™',
  'Ms. La Puente ™',
  'Ms. La Quinta ™',
  'Ms. La Verne ™',
  'Ms. Lafayette ™',
  'Ms. Laguna Beach ™',
  'Ms. Laguna Hills ™',
  'Ms. Laguna Niguel ™',
  'Ms. Laguna Woods ™',
  'Ms. Lake Elsinore ™',
  'Ms. Lake Forest ™',
  'Ms. Lakeport ™',
  'Ms. Lakewood ™',
  'Ms. Lancaster ™',
  'Ms. Larkspur ™',
  'Ms. Lathrop ™',
  'Ms. Lawndale ™',
  'Ms. Lemon Grove ™',
  'Ms. Lemoore ™',
  'Ms. Lincoln ™',
  'Ms. Lindsay ™',
  'Ms. Live Oak ™',
  'Ms. Livermore ™',
  'Ms. Livingston ™',
  'Ms. Lodi ™',
  'Ms. Loma Linda ™',
  'Ms. Lomita ™',
  'Ms. Lompoc ™',
  'Ms. Long Beach ™',
  'Ms. Loomis ™',
  'Ms. Los Alamitos ™',
  'Ms. Los Altos ™',
  'Ms. Los Altos Hills ™',
  'Ms. Los Angeles ™',
  'Ms. Los Banos ™',
  'Ms. Los Gatos ™',
  'Ms. Loyalton ™',
  'Ms. Lynwood ™',
  'Ms. Madera ™',
  'Ms. Malibu ™',
  'Ms. Mammoth Lakes ™',
  'Ms. Manhattan Beach ™',
  'Ms. Manteca ™',
  'Ms. Maricopa ™',
  'Ms. Marina ™',
  'Ms. Martinez ™',
  'Ms. Marysville ™',
  'Ms. Maywood ™',
  'Ms. McFarland ™',
  'Ms. Mendota ™',
  'Ms. Menifee ™',
  'Ms. Menlo Park ™',
  'Ms. Merced ™',
  'Ms. Mill Valley ™',
  'Ms. Millbrae ™',
  'Ms. Milpitas ™',
  'Ms. Mission Viejo ™',
  'Ms. Modesto ™',
  'Ms. Monrovia ™',
  'Ms. Montague ™',
  'Ms. Montclair ™',
  'Ms. Monte Sereno ™',
  'Ms. Montebello ™',
  'Ms. Monterey ™',
  'Ms. Monterey Park ™',
  'Ms. Moorpark ™',
  'Ms. Moraga ™',
  'Ms. Moreno Valley ™',
  'Ms. Morgan Hill ™',
  'Ms. Morro Bay ™',
  'Ms. Mount Shasta ™',
  'Ms. Mountain View ™',
  'Ms. Murrieta ™',
  'Ms. Napa ™',
  'Ms. National City ™',
  'Ms. Needles ™',
  'Ms. Nevada City ™',
  'Ms. Newark ™',
  'Ms. Newman ™',
  'Ms. Newport Beach ™',
  'Ms. Norco ™',
  'Ms. Norwalk ™',
  'Ms. Novato ™',
  'Ms. Oakdale ™',
  'Ms. Oakland ™',
  'Ms. Oakley ™',
  'Ms. Oceanside ™',
  'Ms. Ojai ™',
  'Ms. Ontario ™',
  'Ms. Orange ™',
  'Ms. Orange Cove ™',
  'Ms. Orinda ™',
  'Ms. Orland ™',
  'Ms. Oroville ™',
  'Ms. Oxnard ™',
  'Ms. Pacific Grove ™',
  'Ms. Pacifica ™',
  'Ms. Palm Desert ™',
  'Ms. Palm Springs ™',
  'Ms. Palmdale ™',
  'Ms. Palo Alto ™',
  'Ms. Palos Verdes Estates ™',
  'Ms. Paradise ™',
  'Ms. Paramount ™',
  'Ms. Parlier ™',
  'Ms. Pasadena ™',
  'Ms. Paso Robles ™',
  'Ms. Patterson ™',
  'Ms. Perris ™',
  'Ms. Petaluma ™',
  'Ms. Pico Rivera ™',
  'Ms. Piedmont ™',
  'Ms. Pinole ™',
  'Ms. Pismo Beach ™',
  'Ms. Pittsburg ™',
  'Ms. Placentia ™',
  'Ms. Placerville ™',
  'Ms. Pleasant Hill ™',
  'Ms. Pleasanton ™',
  'Ms. Plymouth ™',
  'Ms. Point Arena ™',
  'Ms. Pomona ™',
  'Ms. Port Hueneme ™',
  'Ms. Porterville ™',
  'Ms. Portola ™',
  'Ms. Portola Valley ™',
  'Ms. Poway ™',
  'Ms. Rancho Cordova ™',
  'Ms. Rancho Cucamonga ™',
  'Ms. Rancho Mirage ™',
  'Ms. Rancho Palos Verdes ™',
  'Ms. Rancho Santa Margarita ™',
  'Ms. Red Bluff ™',
  'Ms. Redding ™',
  'Ms. Redlands ™',
  'Ms. Redondo Beach ™',
  'Ms. Redwood City ™',
  'Ms. Reedley ™',
  'Ms. Rialto ™',
  'Ms. Richmond ™',
  'Ms. Ridgecrest ™',
  'Ms. Rio Dell ™',
  'Ms. Rio Vista ™',
  'Ms. Ripon ™',
  'Ms. Riverbank ™',
  'Ms. Riverside ™',
  'Ms. Rocklin ™',
  'Ms. Rohnert Park ™',
  'Ms. Rolling Hills ™',
  'Ms. Rolling Hills Estates ™',
  'Ms. Rosemead ™',
  'Ms. Roseville ™',
  'Ms. Ross ™',
  'Ms. Sacramento ™',
  'Ms. St. Helena ™',
  'Ms. Salinas ™',
  'Ms. San Anselmo ™',
  'Ms. San Bernardino ™',
  'Ms. San Bruno ™',
  'Ms. San Carlos ™',
  'Ms. San Clemente ™',
  'Ms. San Diego ™',
  'Ms. San Dimas ™',
  'Ms. San Fernando ™',
  'Ms. San Francisco ™',
  'Ms. San Gabriel ™',
  'Ms. San Jacinto ™',
  'Ms. San Joaquin ™',
  'Ms. San Jose ™',
  'Ms. San Juan Bautista ™',
  'Ms. San Juan Capistrano ™',
  'Ms. San Leandro ™',
  'Ms. San Luis Obispo ™',
  'Ms. San Marcos ™',
  'Ms. San Marino ™',
  'Ms. San Mateo ™',
  'Ms. San Pablo ™',
  'Ms. San Rafael ™',
  'Ms. San Ramon ™',
  'Ms. Sand City ™',
  'Ms. Sanger ™',
  'Ms. Santa Ana ™',
  'Ms. Santa Barbara ™',
  'Ms. Santa Clara ™',
  'Ms. Santa Clarita ™',
  'Ms. Santa Cruz ™',
  'Ms. Santa Fe Springs ™',
  'Ms. Santa Maria ™',
  'Ms. Santa Monica ™',
  'Ms. Santa Paula ™',
  'Ms. Santa Rosa ™',
  'Ms. Santee ™',
  'Ms. Saratoga ™',
  'Ms. Sausalito ™',
  'Ms. Scotts Valley ™',
  'Ms. Seal Beach ™',
  'Ms. Seaside ™',
  'Ms. Sebastopol ™',
  'Ms. Selma ™',
  'Ms. Shafter ™',
  'Ms. Shasta Lake ™',
  'Ms. Sierra Madre ™',
  'Ms. Signal Hill ™',
  'Ms. Simi Valley ™',
  'Ms. Solana Beach ™',
  'Ms. Soledad ™',
  'Ms. Solvang ™',
  'Ms. Sonoma ™',
  'Ms. Sonora ™',
  'Ms. South El Monte ™',
  'Ms. South Gate ™',
  'Ms. South Lake Tahoe ™',
  'Ms. South Pasadena ™',
  'Ms. South San Francisco ™',
  'Ms. Stanton ™',
  'Ms. Stockton ™',
  'Ms. Suisun City ™',
  'Ms. Sunnyvale ™',
  'Ms. Susanville ™',
  'Ms. Sutter Creek ™',
  'Ms. Taft ™',
  'Ms. Tehachapi ™',
  'Ms. Tehama ™',
  'Ms. Temecula ™',
  'Ms. Temple City ™',
  'Ms. Thousand Oaks ™',
  'Ms. Tiburon ™',
  'Ms. Torrance ™',
  'Ms. Tracy ™',
  'Ms. Trinidad ™',
  'Ms. Truckee ™',
  'Ms. Tulare ™',
  'Ms. Tulelake ™',
  'Ms. Turlock ™',
  'Ms. Tustin ™',
  'Ms. Twentynine Palms ™',
  'Ms. Ukiah ™',
  'Ms. Union City ™',
  'Ms. Upland ™',
  'Ms. Vacaville ™',
  'Ms. Vallejo ™',
  'Ms. Vernon ™',
  'Ms. Victorville ™',
  'Ms. Villa Park ™',
  'Ms. Visalia ™',
  'Ms. Vista ™',
  'Ms. Walnut ™',
  'Ms. Walnut Creek ™',
  'Ms. Wasco ™',
  'Ms. Waterford ™',
  'Ms. Watsonville ™',
  'Ms. Weed ™',
  'Ms. West Covina ™',
  'Ms. West Hollywood ™',
  'Ms. West Sacramento ™',
  'Ms. Westlake Village ™',
  'Ms. Westminster ™',
  'Ms. Westmorland ™',
  'Ms. Wheatland ™',
  'Ms. Whittier ™',
  'Ms. Williams ™',
  'Ms. Willits ™',
  'Ms. Willows ™',
  'Ms. Windsor ™',
  'Ms. Winters ™',
  'Ms. Woodlake ™',
  'Ms. Woodland ™',
  'Ms. Woodside ™',
  'Ms. Yorba Linda ™',
  'Ms. Yountville ™',
  'Ms. Yreka ™',
  'Ms. Yuba City ™',
  'Ms. Yucaipa ™',
  'Ms. Yucca Valley ™',
  'Ms. Inland Empire ™',
  'Ms. San Gabriel Valley ™',
]

export const California: Block = {
  slug: 'california',
  interfaceName: 'CaliforniaBlock',
  labels: {
    singular: 'California',
    plural: 'California Blocks',
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      label: 'Section Title',
      defaultValue: 'California',
      required: true,
    },
    {
      name: 'mrDesignations',
      type: 'array',
      label: 'Mr. California Cities',
      admin: {
        description: 'List of Mr. California city designations',
        initCollapsed: true,
      },
      defaultValue: mrCities.map((city) => ({ title: city, link: '#' })),
      fields: [
        {
          name: 'title',
          type: 'text',
          label: 'Designation Title',
          required: true,
          admin: {
            placeholder: 'e.g., Mr. Los Angeles ™',
          },
        },
        {
          name: 'link',
          type: 'text',
          label: 'Link URL',
          admin: {
            placeholder: 'e.g., /designations/mr-los-angeles',
          },
        },
      ],
    },
    {
      name: 'msDesignations',
      type: 'array',
      label: 'Ms. California Cities',
      admin: {
        description: 'List of Ms. California city designations',
        initCollapsed: true,
      },
      defaultValue: msCities.map((city) => ({ title: city, link: '#' })),
      fields: [
        {
          name: 'title',
          type: 'text',
          label: 'Designation Title',
          required: true,
          admin: {
            placeholder: 'e.g., Ms. Los Angeles ™',
          },
        },
        {
          name: 'link',
          type: 'text',
          label: 'Link URL',
          admin: {
            placeholder: 'e.g., /designations/ms-los-angeles',
          },
        },
      ],
    },
  ],
}
