/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    agents: Agent;
    states: State;
    designations: Designation;
    testimonials: Testimonial;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'plugin-ai-instructions': PluginAiInstruction;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    states: StatesSelect<false> | StatesSelect<true>;
    designations: DesignationsSelect<false> | DesignationsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'plugin-ai-instructions': PluginAiInstructionsSelect<false> | PluginAiInstructionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
            /**
             * Choose a hover color for the button
             */
            hoverColor?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Color for headings (H1, H2) - use color picker
     */
    headingColor?: string | null;
    /**
     * Color for subtitle/small text above heading
     */
    subtitleColor?: string | null;
    /**
     * Color for paragraphs/body text
     */
    paragraphColor?: string | null;
    media?: (number | null) | Media;
    /**
     * Logo displayed below the hero text (e.g., DLE Network logo)
     */
    logo?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | HomeValueFormBlock
    | TestimonialsBlock
    | ServicesGridBlock
    | AgentGalleryBlock
    | FAQBlock
    | AgentBlogBlock
    | AgentContactBlock
    | DirectoryListingBlock
    | HomepageBlogBlock
    | VideoEmbedBlock
    | TeamSectionBlock
    | PartnersLogosBlock
    | FeaturedAgentsBlock
    | PageBlogBlock
    | AboutSectionBlock
    | SolutionsSectionBlock
    | ServicesSectionBlock
    | FeaturedTestimonialBlock
    | ArticlesSectionBlock
    | ArticlesSidebarBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  /**
   * Select where this post should appear
   */
  postType: 'main' | 'agent' | 'syndicated';
  /**
   * Display this post on the main website homepage
   */
  showOnHomepage?: boolean | null;
  /**
   * Associate this post with a specific agent's super page blog
   */
  agent?: (number | null) | Agent;
  /**
   * Select multiple agents to syndicate/copy this post to their pages
   */
  syndicatedAgents?: (number | Agent)[] | null;
  /**
   * Highlight this post as featured
   */
  isFeatured?: boolean | null;
  /**
   * Display this post on specific pages (e.g., Google SEO Services page)
   */
  relatedPages?: (number | Page)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  /**
   * Agent's full legal name (e.g., Anthony Grynchal)
   */
  name: string;
  /**
   * The designation title (e.g., Mr. Claremont™, Ms. Fresno™)
   */
  displayName: string;
  city: string;
  state: number | State;
  /**
   * Select the designation types for this agent (e.g., Mr. SEO, Mr. Luxury)
   */
  designation?: (number | Designation)[] | null;
  profilePhoto: number | Media;
  heroImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  /**
   * e.g., "TOP RATED REAL ESTATE AGENT IN CLAREMONT"
   */
  tagline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief description for listings and cards
   */
  shortBio?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  workingHours?:
    | {
        day?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
        /**
         * e.g., 7 AM – 9:30 PM
         */
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    twitter?: string | null;
    pinterest?: string | null;
    tiktok?: string | null;
    googleMaps?: string | null;
  };
  /**
   * e.g., DRE# 01873626
   */
  dreLicense?: string | null;
  brokerage?: {
    name?: string | null;
    logo?: (number | null) | Media;
  };
  certifications?:
    | {
        /**
         * e.g., Certified Luxury Home Marketing Specialist
         */
        title: string;
        /**
         * e.g., CLHMS
         */
        abbreviation?: string | null;
        id?: string | null;
      }[]
    | null;
  experience?: number | null;
  memberSince?: string | null;
  services?:
    | {
        /**
         * e.g., Home Value & Appraisal Services
         */
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * CloudCMA or similar home value widget URL
   */
  homeValueWidgetUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Show this agent in featured sections
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "states".
 */
export interface State {
  id: number;
  /**
   * e.g., California, Texas, Florida
   */
  name: string;
  /**
   * e.g., CA, TX, FL
   */
  abbreviation: string;
  country: 'usa' | 'canada' | 'uk' | 'australia' | 'new-zealand' | 'uae';
  /**
   * Check if this is an unincorporated area directory
   */
  isUnincorporated?: boolean | null;
  description?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  headerImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designations".
 */
export interface Designation {
  id: number;
  /**
   * e.g., Mr. SEO™, Mrs. Luxury™, Mr. Listings™
   */
  title: string;
  prefix: 'mr' | 'mrs' | 'ms';
  category:
    | 'city'
    | 'seo'
    | 'luxury'
    | 'listings'
    | 'new-build'
    | 'title'
    | 'mobile-home'
    | 'appraisal'
    | 'fix-flip'
    | 'marketing'
    | 'open-house'
    | 'offers'
    | 'nationwide'
    | 'efficiency'
    | 'other';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief description for cards and listings
   */
  shortDescription?: string | null;
  icon?: (number | null) | Media;
  /**
   * For nested dropdown menus (e.g., Mr. Listings → Mr. Marketing)
   */
  parentDesignation?: (number | null) | Designation;
  headerImage?: (number | null) | Media;
  homeValueFormTitle?: string | null;
  homeValueFormDescription?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Show in the main navigation dropdown
   */
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          /**
           * Choose a hover color for the button
           */
          hoverColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          /**
           * Choose a hover color for the button
           */
          hoverColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeValueFormBlock".
 */
export interface HomeValueFormBlock {
  title: string;
  description?: string | null;
  inputPlaceholder?: string | null;
  buttonText?: string | null;
  /**
   * CloudCMA or similar home value widget URL. Leave blank to use internal form.
   */
  widgetUrl?: string | null;
  backgroundImage?: (number | null) | Media;
  style?: ('centered' | 'left' | 'sidebar') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeValueForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  title?: string | null;
  subtitle?: string | null;
  /**
   * Leave blank to show all featured testimonials
   */
  agent?: (number | null) | Agent;
  /**
   * Manually select testimonials. Leave blank to auto-populate from agent.
   */
  testimonials?: (number | Testimonial)[] | null;
  limit?: number | null;
  layout?: ('grid' | 'carousel' | 'list') | null;
  showRatings?: boolean | null;
  showPhotos?: boolean | null;
  showSource?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  clientPhoto?: (number | null) | Media;
  /**
   * Is this reviewer a Google Local Guide?
   */
  isLocalGuide?: boolean | null;
  rating: number;
  review: string;
  /**
   * The agent this testimonial belongs to
   */
  agent: number | Agent;
  source?: ('google' | 'yelp' | 'zillow' | 'realtor' | 'facebook' | 'direct' | 'other') | null;
  /**
   * Link to the original review
   */
  sourceUrl?: string | null;
  date?: string | null;
  /**
   * Show this testimonial prominently
   */
  featured?: boolean | null;
  /**
   * Only approved testimonials will be displayed
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  title?: string | null;
  /**
   * Optional subtitle text below the main title
   */
  subtitle?: string | null;
  enableButton?: boolean | null;
  headerLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
    /**
     * Choose a hover color for the button
     */
    hoverColor?: string | null;
  };
  buttonStyle?: ('red' | 'dark' | 'outline') | null;
  services?:
    | {
        /**
         * e.g., Home Value & Appraisal Services
         */
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?: (number | null) | Media;
        link?: {
          type?: ('none' | 'internal' | 'external') | null;
          url?: string | null;
          page?: (number | null) | Page;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  layout?: ('twoColumn' | 'threeColumn' | 'fourColumn' | 'alternating') | null;
  showIcons?: boolean | null;
  /**
   * Border radius for the service cards in pixels (e.g., 0 for square, 8 for rounded)
   */
  cardBorderRadius?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentGalleryBlock".
 */
export interface AgentGalleryBlock {
  title?: string | null;
  /**
   * Auto-populate gallery from agent profile. Leave blank to use manual selection.
   */
  agent?: (number | null) | Agent;
  /**
   * Manually select images. Will be used if no agent is selected.
   */
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid' | 'masonry' | 'carousel') | null;
  columns?: ('2' | '3' | '4') | null;
  enableLightbox?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'agentGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  /**
   * Auto-populate FAQs from agent profile. Leave blank to use manual selection.
   */
  agent?: (number | null) | Agent;
  /**
   * Manually add FAQs. Will be used if no agent is selected.
   */
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  layout?: ('accordion' | 'twoColumn' | 'list') | null;
  defaultOpen?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentBlogBlock".
 */
export interface AgentBlogBlock {
  title?: string | null;
  /**
   * Show blog posts for this agent. Leave blank to show general posts.
   */
  agent?: (number | null) | Agent;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  layout?: ('grid' | 'list' | 'featured') | null;
  showLoadMore?: boolean | null;
  showDate?: boolean | null;
  showAuthor?: boolean | null;
  showExcerpt?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'agentBlog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentContactBlock".
 */
export interface AgentContactBlock {
  /**
   * Auto-populate contact info from agent profile.
   */
  agent?: (number | null) | Agent;
  title?: string | null;
  showBio?: boolean | null;
  showPhoto?: boolean | null;
  showSocialLinks?: boolean | null;
  showWorkingHours?: boolean | null;
  showContactForm?: boolean | null;
  layout?: ('twoColumn' | 'sidebar' | 'fullWidth') | null;
  backgroundColor?: ('white' | 'gray' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'agentContact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DirectoryListingBlock".
 */
export interface DirectoryListingBlock {
  title?: string | null;
  listingType: 'agents' | 'states' | 'designations';
  /**
   * Show only agents from this state
   */
  filterByState?: (number | null) | State;
  /**
   * Show only agents with this designation
   */
  filterByDesignation?: (number | null) | Designation;
  filterByCountry?: ('all' | 'usa' | 'canada' | 'uk' | 'australia' | 'new-zealand' | 'uae') | null;
  layout?: ('multiColumn' | 'grid' | 'alphabetical') | null;
  columns?: ('2' | '3' | '4' | '5') | null;
  showApplyButton?: boolean | null;
  showInquireButton?: boolean | null;
  applyButtonUrl?: string | null;
  inquireButtonUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'directoryListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageBlogBlock".
 */
export interface HomepageBlogBlock {
  title?: string | null;
  subtitle?: string | null;
  limit?: number | null;
  /**
   * Include posts with type "Main Website Blog"
   */
  showMainBlog?: boolean | null;
  /**
   * Include syndicated posts with "Show on Homepage" checked
   */
  showSyndicatedOnHomepage?: boolean | null;
  showFeaturedOnly?: boolean | null;
  layout?: ('grid' | 'list' | 'featured') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageBlog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  /**
   * YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=xxxxx)
   */
  videoUrl: string;
  /**
   * Optional title displayed above the video
   */
  title?: string | null;
  aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
  maxWidth?: ('small' | 'medium' | 'large' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamSectionBlock".
 */
export interface TeamSectionBlock {
  eyebrow?: string | null;
  title?: string | null;
  members?:
    | {
        name: string;
        role?: string | null;
        photo: number | Media;
        bio?: string | null;
        linkedIn?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersLogosBlock".
 */
export interface PartnersLogosBlock {
  eyebrow?: string | null;
  title?: string | null;
  logos?:
    | {
        name: string;
        logo: number | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  style?: ('carousel' | 'grid' | 'inline') | null;
  grayscale?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnersLogos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedAgentsBlock".
 */
export interface FeaturedAgentsBlock {
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  displayMode?: ('auto' | 'manual' | 'designation' | 'custom') | null;
  selectedAgents?: (number | Agent)[] | null;
  /**
   * Show agents with this designation
   */
  designation?: (number | null) | Designation;
  /**
   * Add custom members with photos and names
   */
  customMembers?:
    | {
        /**
         * e.g., Mr. Chatsworth, Ms. Fort Wayne
         */
        name: string;
        photo: number | Media;
        /**
         * Link when clicking on the member
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  limit?: number | null;
  layout?: ('carousel' | 'grid') | null;
  showDesignation?: boolean | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  /**
   * Section background color (e.g., #f9fafb for light gray)
   */
  backgroundColor?: string | null;
  eyebrowColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredAgents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBlogBlock".
 */
export interface PageBlogBlock {
  title?: string | null;
  subtitle?: string | null;
  displayMode?: ('auto' | 'category' | 'manual') | null;
  /**
   * Filter posts by these categories
   */
  categories?: (number | Category)[] | null;
  selectedPosts?: (number | Post)[] | null;
  limit?: number | null;
  layout?: ('grid' | 'list' | 'compact') | null;
  showReadMore?: boolean | null;
  showDate?: boolean | null;
  showExcerpt?: boolean | null;
  ctaLabel?: string | null;
  /**
   * Leave empty to hide the button
   */
  ctaLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageBlog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSectionBlock".
 */
export interface AboutSectionBlock {
  /**
   * Color for the section heading (default: red)
   */
  headingColor?: string | null;
  heading: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  enableButton?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
    /**
     * Choose a hover color for the button
     */
    hoverColor?: string | null;
  };
  /**
   * Image displayed on the right side of the section
   */
  image: number | Media;
  imagePosition?: ('left' | 'right') | null;
  /**
   * Background color for the section
   */
  backgroundColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionsSectionBlock".
 */
export interface SolutionsSectionBlock {
  /**
   * Image displayed on the left (e.g., Agent Training infographic)
   */
  image: number | Media;
  title: string;
  solutions?:
    | {
        /**
         * e.g., "#1 – Be Remembered"
         */
        heading: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  enableButton?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
    /**
     * Choose a hover color for the button
     */
    hoverColor?: string | null;
  };
  buttonStyle?: ('dark' | 'red' | 'outline') | null;
  imagePosition?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesSectionBlock".
 */
export interface ServicesSectionBlock {
  /**
   * Small text above the main title (e.g., "Our Services")
   */
  eyebrow?: string | null;
  eyebrowColor?: string | null;
  title: string;
  /**
   * Optional subtitle text below the main title
   */
  subtitle?: string | null;
  enableButton?: boolean | null;
  headerLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
    /**
     * Choose a hover color for the button
     */
    hoverColor?: string | null;
  };
  buttonStyle?: ('red' | 'dark' | 'outline') | null;
  services?:
    | {
        /**
         * Icon image for the service card
         */
        icon?: (number | null) | Media;
        /**
         * e.g., "Google Business Profile Optimization"
         */
        title: string;
        titleColor?: string | null;
        description: string;
        enableLink?: boolean | null;
        serviceLink?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          /**
           * Choose a hover color for the button
           */
          hoverColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Number of columns in the service cards grid
   */
  columns?: ('2' | '3' | '4') | null;
  /**
   * Border radius for the service cards in pixels (e.g., 0 for square, 16 for rounded)
   */
  cardBorderRadius?: number | null;
  backgroundColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedTestimonialBlock".
 */
export interface FeaturedTestimonialBlock {
  /**
   * Small text above the title (e.g., "We Love Them")
   */
  eyebrow?: string | null;
  eyebrowColor?: string | null;
  title?: string | null;
  testimonials?:
    | {
        photo?: (number | null) | Media;
        /**
         * The testimonial text
         */
        quote: string;
        /**
         * e.g., "Brianna L"
         */
        clientName: string;
        /**
         * e.g., "Ms. Glendora" or "Real Estate Agent, Los Angeles"
         */
        clientTitle?: string | null;
        id?: string | null;
      }[]
    | null;
  nameColor?: string | null;
  photoPosition?: ('left' | 'right') | null;
  backgroundColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredTestimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticlesSectionBlock".
 */
export interface ArticlesSectionBlock {
  title?: string | null;
  displayMode?: ('latest' | 'category' | 'manual') | null;
  /**
   * Filter posts by these categories
   */
  categories?: (number | Category)[] | null;
  selectedPosts?: (number | Post)[] | null;
  limit?: number | null;
  columns?: ('2' | '3' | '4') | null;
  showAuthor?: boolean | null;
  showDate?: boolean | null;
  showExcerpt?: boolean | null;
  showReadMore?: boolean | null;
  enablePagination?: boolean | null;
  postsPerPage?: number | null;
  titleColor?: string | null;
  readMoreColor?: string | null;
  backgroundColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articlesSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticlesSidebarBlock".
 */
export interface ArticlesSidebarBlock {
  title?: string | null;
  displayMode?: ('latest' | 'category' | 'manual') | null;
  /**
   * Filter posts by these categories
   */
  categories?: (number | Category)[] | null;
  selectedPosts?: (number | Post)[] | null;
  limit?: number | null;
  columns?: ('1' | '2') | null;
  showAuthor?: boolean | null;
  showDate?: boolean | null;
  showExcerpt?: boolean | null;
  showReadMore?: boolean | null;
  enablePagination?: boolean | null;
  postsPerPage?: number | null;
  showSidebar?: boolean | null;
  /**
   * Select an agent to display their contact info in the sidebar
   */
  sidebarAgent?: (number | null) | Agent;
  showContactInfo?: boolean | null;
  showSocialLinks?: boolean | null;
  showFeaturedOn?: boolean | null;
  featuredOnLogos?:
    | {
        logo: number | Media;
        name?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  titleColor?: string | null;
  titleBgColor?: string | null;
  accentColor?: string | null;
  backgroundColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articlesSidebar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions".
 */
export interface PluginAiInstruction {
  id: number;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'schema-path'?: string | null;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'field-type'?: ('text' | 'textarea' | 'upload' | 'richText') | null;
  'relation-to'?: string | null;
  'model-id'?: ('Oai-text' | 'dall-e' | 'gpt-image-1' | 'tts' | 'Oai-object') | null;
  /**
   * Please reload your collection after applying the changes
   */
  disabled?: boolean | null;
  /**
   * Click 'Compose' to run this custom prompt and generate content
   */
  prompt?: string | null;
  images?:
    | {
        /**
         * Please make sure the image is publicly accessible.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  system?: string | null;
  layout?: string | null;
  'Oai-text-settings'?: {
    model?:
      | ('gpt-5' | 'gpt-5-mini' | 'gpt-5-nano' | 'gpt-4.1' | 'gpt-4o' | 'gpt-4-turbo' | 'gpt-4o-mini' | 'gpt-3.5-turbo')
      | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  'dalle-e-settings'?: {
    version?: ('dall-e-3' | 'dall-e-2') | null;
    size?: ('256x256' | '512x512' | '1024x1024' | '1792x1024' | '1024x1792') | null;
    style?: ('vivid' | 'natural') | null;
    'enable-prompt-optimization'?: boolean | null;
  };
  'gpt-image-1-settings'?: {
    version?: 'gpt-image-1' | null;
    size?: ('1024x1024' | '1024x1536' | '1536x1024' | 'auto') | null;
    quality?: ('low' | 'medium' | 'high' | 'auto') | null;
    output_format?: ('png' | 'jpeg' | 'webp') | null;
    output_compression?: number | null;
    background?: ('white' | 'transparent') | null;
    moderation?: ('auto' | 'low') | null;
  };
  'Oai-tts-settings'?: {
    voice?: ('alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer') | null;
    model?: ('tts-1' | 'tts-1-hd') | null;
    response_format?: ('mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm') | null;
    speed?: number | null;
  };
  'Oai-object-settings'?: {
    model?:
      | ('gpt-5' | 'gpt-5-mini' | 'gpt-5-nano' | 'gpt-4.1' | 'gpt-4o' | 'gpt-4-turbo' | 'gpt-4o-mini' | 'gpt-3.5-turbo')
      | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'states';
        value: number | State;
      } | null)
    | ({
        relationTo: 'designations';
        value: number | Designation;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'plugin-ai-instructions';
        value: number | PluginAiInstruction;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                    hoverColor?: T;
                  };
              id?: T;
            };
        headingColor?: T;
        subtitleColor?: T;
        paragraphColor?: T;
        media?: T;
        logo?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        homeValueForm?: T | HomeValueFormBlockSelect<T>;
        testimonialsBlock?: T | TestimonialsBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        agentGallery?: T | AgentGalleryBlockSelect<T>;
        faqBlock?: T | FAQBlockSelect<T>;
        agentBlog?: T | AgentBlogBlockSelect<T>;
        agentContact?: T | AgentContactBlockSelect<T>;
        directoryListing?: T | DirectoryListingBlockSelect<T>;
        homepageBlog?: T | HomepageBlogBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        teamSection?: T | TeamSectionBlockSelect<T>;
        partnersLogos?: T | PartnersLogosBlockSelect<T>;
        featuredAgents?: T | FeaturedAgentsBlockSelect<T>;
        pageBlog?: T | PageBlogBlockSelect<T>;
        aboutSection?: T | AboutSectionBlockSelect<T>;
        solutionsSection?: T | SolutionsSectionBlockSelect<T>;
        servicesSection?: T | ServicesSectionBlockSelect<T>;
        featuredTestimonial?: T | FeaturedTestimonialBlockSelect<T>;
        articlesSection?: T | ArticlesSectionBlockSelect<T>;
        articlesSidebar?: T | ArticlesSidebarBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              hoverColor?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              hoverColor?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeValueFormBlock_select".
 */
export interface HomeValueFormBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  inputPlaceholder?: T;
  buttonText?: T;
  widgetUrl?: T;
  backgroundImage?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  agent?: T;
  testimonials?: T;
  limit?: T;
  layout?: T;
  showRatings?: T;
  showPhotos?: T;
  showSource?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  enableButton?: T;
  headerLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        hoverColor?: T;
      };
  buttonStyle?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        link?:
          | T
          | {
              type?: T;
              url?: T;
              page?: T;
              label?: T;
            };
        id?: T;
      };
  layout?: T;
  showIcons?: T;
  cardBorderRadius?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentGalleryBlock_select".
 */
export interface AgentGalleryBlockSelect<T extends boolean = true> {
  title?: T;
  agent?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  columns?: T;
  enableLightbox?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  agent?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  layout?: T;
  defaultOpen?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentBlogBlock_select".
 */
export interface AgentBlogBlockSelect<T extends boolean = true> {
  title?: T;
  agent?: T;
  categories?: T;
  limit?: T;
  layout?: T;
  showLoadMore?: T;
  showDate?: T;
  showAuthor?: T;
  showExcerpt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentContactBlock_select".
 */
export interface AgentContactBlockSelect<T extends boolean = true> {
  agent?: T;
  title?: T;
  showBio?: T;
  showPhoto?: T;
  showSocialLinks?: T;
  showWorkingHours?: T;
  showContactForm?: T;
  layout?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DirectoryListingBlock_select".
 */
export interface DirectoryListingBlockSelect<T extends boolean = true> {
  title?: T;
  listingType?: T;
  filterByState?: T;
  filterByDesignation?: T;
  filterByCountry?: T;
  layout?: T;
  columns?: T;
  showApplyButton?: T;
  showInquireButton?: T;
  applyButtonUrl?: T;
  inquireButtonUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageBlogBlock_select".
 */
export interface HomepageBlogBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  limit?: T;
  showMainBlog?: T;
  showSyndicatedOnHomepage?: T;
  showFeaturedOnly?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  videoUrl?: T;
  title?: T;
  aspectRatio?: T;
  maxWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamSectionBlock_select".
 */
export interface TeamSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  members?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        bio?: T;
        linkedIn?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersLogosBlock_select".
 */
export interface PartnersLogosBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  logos?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  style?: T;
  grayscale?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedAgentsBlock_select".
 */
export interface FeaturedAgentsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  displayMode?: T;
  selectedAgents?: T;
  designation?: T;
  customMembers?:
    | T
    | {
        name?: T;
        photo?: T;
        link?: T;
        id?: T;
      };
  limit?: T;
  layout?: T;
  showDesignation?: T;
  ctaLabel?: T;
  ctaLink?: T;
  backgroundColor?: T;
  eyebrowColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBlogBlock_select".
 */
export interface PageBlogBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  displayMode?: T;
  categories?: T;
  selectedPosts?: T;
  limit?: T;
  layout?: T;
  showReadMore?: T;
  showDate?: T;
  showExcerpt?: T;
  ctaLabel?: T;
  ctaLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSectionBlock_select".
 */
export interface AboutSectionBlockSelect<T extends boolean = true> {
  headingColor?: T;
  heading?: T;
  content?: T;
  enableButton?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        hoverColor?: T;
      };
  image?: T;
  imagePosition?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionsSectionBlock_select".
 */
export interface SolutionsSectionBlockSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  solutions?:
    | T
    | {
        heading?: T;
        description?: T;
        id?: T;
      };
  enableButton?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        hoverColor?: T;
      };
  buttonStyle?: T;
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesSectionBlock_select".
 */
export interface ServicesSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  eyebrowColor?: T;
  title?: T;
  subtitle?: T;
  enableButton?: T;
  headerLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        hoverColor?: T;
      };
  buttonStyle?: T;
  services?:
    | T
    | {
        icon?: T;
        title?: T;
        titleColor?: T;
        description?: T;
        enableLink?: T;
        serviceLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              hoverColor?: T;
            };
        id?: T;
      };
  columns?: T;
  cardBorderRadius?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedTestimonialBlock_select".
 */
export interface FeaturedTestimonialBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  eyebrowColor?: T;
  title?: T;
  testimonials?:
    | T
    | {
        photo?: T;
        quote?: T;
        clientName?: T;
        clientTitle?: T;
        id?: T;
      };
  nameColor?: T;
  photoPosition?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticlesSectionBlock_select".
 */
export interface ArticlesSectionBlockSelect<T extends boolean = true> {
  title?: T;
  displayMode?: T;
  categories?: T;
  selectedPosts?: T;
  limit?: T;
  columns?: T;
  showAuthor?: T;
  showDate?: T;
  showExcerpt?: T;
  showReadMore?: T;
  enablePagination?: T;
  postsPerPage?: T;
  titleColor?: T;
  readMoreColor?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticlesSidebarBlock_select".
 */
export interface ArticlesSidebarBlockSelect<T extends boolean = true> {
  title?: T;
  displayMode?: T;
  categories?: T;
  selectedPosts?: T;
  limit?: T;
  columns?: T;
  showAuthor?: T;
  showDate?: T;
  showExcerpt?: T;
  showReadMore?: T;
  enablePagination?: T;
  postsPerPage?: T;
  showSidebar?: T;
  sidebarAgent?: T;
  showContactInfo?: T;
  showSocialLinks?: T;
  showFeaturedOn?: T;
  featuredOnLogos?:
    | T
    | {
        logo?: T;
        name?: T;
        link?: T;
        id?: T;
      };
  titleColor?: T;
  titleBgColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  postType?: T;
  showOnHomepage?: T;
  agent?: T;
  syndicatedAgents?: T;
  isFeatured?: T;
  relatedPages?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  displayName?: T;
  city?: T;
  state?: T;
  designation?: T;
  profilePhoto?: T;
  heroImage?: T;
  logo?: T;
  tagline?: T;
  bio?: T;
  shortBio?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  workingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        twitter?: T;
        pinterest?: T;
        tiktok?: T;
        googleMaps?: T;
      };
  dreLicense?: T;
  brokerage?:
    | T
    | {
        name?: T;
        logo?: T;
      };
  certifications?:
    | T
    | {
        title?: T;
        abbreviation?: T;
        id?: T;
      };
  experience?: T;
  memberSince?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  homeValueWidgetUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  _status?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "states_select".
 */
export interface StatesSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  country?: T;
  isUnincorporated?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  headerImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designations_select".
 */
export interface DesignationsSelect<T extends boolean = true> {
  title?: T;
  prefix?: T;
  category?: T;
  description?: T;
  shortDescription?: T;
  icon?: T;
  parentDesignation?: T;
  headerImage?: T;
  homeValueFormTitle?: T;
  homeValueFormDescription?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  clientPhoto?: T;
  isLocalGuide?: T;
  rating?: T;
  review?: T;
  agent?: T;
  source?: T;
  sourceUrl?: T;
  date?: T;
  featured?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions_select".
 */
export interface PluginAiInstructionsSelect<T extends boolean = true> {
  'schema-path'?: T;
  'field-type'?: T;
  'relation-to'?: T;
  'model-id'?: T;
  disabled?: T;
  prompt?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  system?: T;
  layout?: T;
  'Oai-text-settings'?:
    | T
    | {
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  'dalle-e-settings'?:
    | T
    | {
        version?: T;
        size?: T;
        style?: T;
        'enable-prompt-optimization'?: T;
      };
  'gpt-image-1-settings'?:
    | T
    | {
        version?: T;
        size?: T;
        quality?: T;
        output_format?: T;
        output_compression?: T;
        background?: T;
        moderation?: T;
      };
  'Oai-tts-settings'?:
    | T
    | {
        voice?: T;
        model?: T;
        response_format?: T;
        speed?: T;
      };
  'Oai-object-settings'?:
    | T
    | {
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        type?: ('link' | 'dropdown') | null;
        /**
         * The label shown in the navigation
         */
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
        };
        dropdownItems?:
          | {
              label: string;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
              };
              /**
               * Enable to add nested sub-items
               */
              hasSubmenu?: boolean | null;
              subItems?:
                | {
                    label: string;
                    link?: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: number | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: number | Post;
                          } | null);
                      url?: string | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Automatically add all active designations to this dropdown
         */
        includeDesignations?: boolean | null;
        /**
         * Automatically add all states to this dropdown
         */
        includeStates?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Links like ADA disclaimer, Sitemap, Privacy Policy, etc.
   */
  legalLinks?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Company name for copyright notice
   */
  copyrightText?: string | null;
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    pinterest?: string | null;
  };
  /**
   * Disclaimer text displayed at the bottom of the footer
   */
  disclaimer?: string | null;
  /**
   * Phone number to display after the disclaimer text
   */
  disclaimerPhone?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        type?: T;
        label?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        dropdownItems?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
              hasSubmenu?: T;
              subItems?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        includeDesignations?: T;
        includeStates?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  legalLinks?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        pinterest?: T;
      };
  disclaimer?: T;
  disclaimerPhone?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}